apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-objects
  namespace: argocd
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: cert-manager
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/k3sforall/Vaultwarden/
    targetRevision: main
    path: infra/cert-manager/objects
    directory:
      recurse: false
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true
      - SkipDryRunOnMissingResource=true
