apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: clusterissuer-vaultwarden
  labels:
    app.kubernetes.io/name: vaultwarden
    app.kubernetes.io/component: cert-manager
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "admin@icanvoca.com"
    privateKeySecretRef:
      name: clusterissuer-vaultwarden-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
        selector:
          dnsNames:
            - svault.icanvoca.com
