apiVersion: v1
kind: PersistentVolume
metadata:
  name: vaultwarden-data-pv
  labels:
    app.kubernetes.io/name: vaultwarden
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: vaultwarden-local-storage
  local:
    path: /var/lib/vaultwarden/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - laptop-nofan
